sshKey_root=$(cat <<EOF
-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
QyNTUxOQAAACAdnbvdHFI98XtvjkqoW122Y8weTnbfsR+wLtH7wRiAugAAAJChmzw+oZs8
PgAAAAtzc2gtZWQyNTUxOQAAACAdnbvdHFI98XtvjkqoW122Y8weTnbfsR+wLtH7wRiAug
AAAEApoa3G/bHxuisT5KwX7hbjz5kYAr57ivMQgX/1DOnwAx2du90cUj3xe2+OSqhbXbZj
zB5Odt+xH7Au0fvBGIC6AAAAC3Jvb3RAbWlsdG9uAQI=
-----END OPENSSH PRIVATE KEY-----
EOF
)
sshPubKey_root=$(cat <<EOF
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIB2du90cUj3xe2+OSqhbXbZjzB5Odt+xH7Au0fvBGIC6 root
EOF
)

sshKey_admin=$(cat <<EOF
-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
QyNTUxOQAAACDsFOhoqNh/R9Y5clK3nTlscLJ7V0HoVEvpYyovLnDawwAAAJB78Ak+e/AJ
PgAAAAtzc2gtZWQyNTUxOQAAACDsFOhoqNh/R9Y5clK3nTlscLJ7V0HoVEvpYyovLnDaww
AAAECNof3QIx0mf9ICNc8BVfgbUlCVPLe0Ogl/CydOliSUAuwU6Gio2H9H1jlyUredOWxw
sntXQehUS+ljKi8ucNrDAAAAC3Jvb3RAbWlsdG9uAQI=
-----END OPENSSH PRIVATE KEY-----
EOF
)
sshPubKey_admin=$(cat <<EOF
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOwU6Gio2H9H1jlyUredOWxwsntXQehUS+ljKi8ucNrD admin
EOF
)

sshKey_dstote=$(cat <<EOF
-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
QyNTUxOQAAACCYgNnK+SwoOnI9zMC1rUZUbq+dZpy/yp9G4lwoXaOIUgAAAJC6nKu8upyr
vAAAAAtzc2gtZWQyNTUxOQAAACCYgNnK+SwoOnI9zMC1rUZUbq+dZpy/yp9G4lwoXaOIUg
AAAEDUVlfaIIWmhTslg4xY3Bt7NPgXjRAkX1ELXEbtB9h9EpiA2cr5LCg6cj3MwLWtRlRu
r51mnL/Kn0biXChdo4hSAAAAC3Jvb3RAbWlsdG9uAQI=
-----END OPENSSH PRIVATE KEY-----
EOF
)
sshPubKey_dstote=$(cat <<EOF
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJiA2cr5LCg6cj3MwLWtRlRur51mnL/Kn0biXChdo4hS dstote
EOF
)

